version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: eden-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.eden1.rule=Host(`eden.donmacaron.net`)
      - traefik.http.routers.eden1.entrypoints=webs
      - traefik.http.routers.eden1.tls.certresolver=myresolver
      - traefik.http.routers.eden2.rule=Host(`eden.donmacaron.net`)
      - traefik.http.routers.eden2.entrypoints=web
      - traefik.http.routers.eden2.middlewares=redirect-to-https     
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.port=443
    networks:
      - traefik-default

# networks:
#   traefik-default:
#     external: true