# docker-compose.dev.yml
version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    image: eden-backend-dev:latest
    working_dir: /app
    volumes:
      - ./backend:/app:delegated
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    command: ["python", "-u", "app.py"]
    networks:
      - eden-net

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:5000
    command: [ "sh", "-c", "npm ci --no-audit --no-fund && npm run dev -- --host 0.0.0.0" ]
    depends_on:
      - backend
    networks:
      - eden-net

networks:
  eden-net:
    driver: bridge

volumes:
  frontend_node_modules:
