version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: eden-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    # If you want to use Traefik externally, don't map ports here; Traefik can route directly to container port 5000
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.eden.rule=Host(`yourdomain.com`)"
    #   - "traefik.http.services.eden.loadbalancer.server.port=5000"
