# backend/Dockerfile.dev
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# # Установим небольшие системные зависимости (при необходимости)
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     build-essential \
#   && rm -rf /var/lib/apt/lists/*

# Скопируем requirements и установим их (быстрый rebuild при изменениях кода)
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip setuptools wheel \
 && pip install --no-cache-dir -r /app/requirements.txt

# Команда по умолчанию (в dev compose мы будем монтировать ./backend поверх /app)
CMD ["python", "-u", "app.py"]
